Repository DazzlingFugu/ember-cli-embedded, pull requests merged in 2021-09, with the labels that each got.

#102 Set up TypeScript lint
  .eslintrc.js
  .prettierignore
  .prettierrc.js
  .template-lintrc.js
  addon/initializers/embedded.ts
  addon/instance-initializers/embedded.ts
  addon/services/embedded.ts
  app/initializers/embedded.js
  app/instance-initializers/embedded.js
  app/services/embedded.js
  config/ember-try.js
  config/environment.js
  ember-cli-build.js
  index.js
  package.json
  testem.js
  tests/dummy/app/app.js
  tests/dummy/app/config/environment.d.ts
  tests/dummy/app/router.js
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/test-helper.ts
  tests/unit/initializers/embedded-test.ts
  tests/unit/instance-initializers/embedded-test.ts
  tests/unit/services/embedded-test.ts
  types/global.d.ts
  yarn.lock
Labels: dependencies

#127 Update and modernise `README`
  README.md
Labels: documentation

#129 Release v2
  package.json
Labels: release

#117 Fix/ new deprecated structure
  addon/initializers/embedded.ts
  package.json
  yarn.lock
Labels: dependencies, ts-types
